sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mbintanveer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mbintanveer/react-test npm test

after_success:
  - docker build -t mbintanveer/multi-client ./client
  - docker build -t mbintanveer/multi-nginx ./nginx
  - docker build -t mbintanveer/multi-server ./server
  - docker build -t mbintanveer/multi-worker ./worker
  # Log in to the docker CLI
  - echo $DOCKER_PASSWORD | docker login -u $DOCKER_ID --password-stdin
  # Take those images and push them to docker hub
  - docker push mbintanveer/multi-client
  - docker push mbintanveer/multi-nginx
  - docker push mbintanveer/multi-server
  - docker push mbintanveer/multi-worker
