sudo: required
services:
  - docker

before_install:
  - docker build -t mbintanveer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test 

after_success:
  - docker build -t mbintanveer/multi-client ./client	
  - docker build -t mbintanveer/multi-nginx ./nginx
  - docker build -t mbintanveer/multi-server ./server
  - docker build -t mbintanveer/multi-worker ./worker

  
